name: Upload diff files
on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get diff
        run: |
            for file in $(git diff ${{github.event.before}}..${{github.event.after}} --name-only) ; do
            echo $file
            aws s3 cp $file s3://articles-for-comprehend-me/ja/
            done
        env:
          AWS_DEFAULT_REGION: 'ap-northeast-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}